services:
  node1:
    build: .
    image: my-kv-store:latest
    ports:
      - "8001:8000"
    environment:
      - MY_ADDRESS=http://node1:8000
  node2:
    build: .
    image: my-kv-store:latest
    ports:
      - "8002:8000"
    environment:
      - MY_ADDRESS=http://node2:8000
  node3:
    build: .
    image: my-kv-store:latest
    ports:
      - "8003:8000"
    environment:
      - MY_ADDRESS=http://node3:8000
  node4:
    build: .
    image: my-kv-store:latest
    ports:
      - "8004:8000"
    environment:
      - MY_ADDRESS=http://node4:8000
  node5:
    build: .
    image: my-kv-store:latest
    ports:
      - "8005:8000"
    environment:
      - MY_ADDRESS=http://node5:8000