
services:
  node1:
    image: my-kv-store:latest
    ports:
      - "8001:8000"
    environment:
      - MY_ADDRESS=http://node1:8000

  node2:
    image: my-kv-store:latest
    ports:
      - "8002:8000"
    environment:
      - MY_ADDRESS=http://node2:8000

  node3:
    image: my-kv-store:latest
    ports:
      - "8003:8000"
    environment:
      - MY_ADDRESS=http://node3:8000